export const jobs = [
  {
    company_name: "Google",
    overview:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cursus turpis massa tincidunt dui ut. Lectus mauris ultrices eros in cursus turpis massa tincidunt. Sit amet consectetur adipiscing elit duis tristique. Neque viverra justo nec ultrices dui sapien eget mi proin. Vitae aliquet nec ullamcorper sit. Consectetur purus ut faucibus pulvinar elementum integer. Duis at tellus at urna condimentum mattis pellentesque. Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Lacus sed turpis tincidunt id.",
    job_desc:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.",
    eligibility:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.",
    exp_yr: "2-3",
    salary: "50000",
    bg_img: `bg-[url('https://t3.ftcdn.net/jpg/05/79/48/52/360_F_579485255_hzHox0stuQmBx5QViwnQqQjk7RD2AJza.jpg')]`,
    job_title: "Software Developer",
    job_type: "Internship",
    location: "India",
    experience: "Fresher",
    time_posted: "4d",
    address: "12, Nico Robbin, Nicobar Islands",
  },
  {
    company_name: "Google",
    overview:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cursus turpis massa tincidunt dui ut. Lectus mauris ultrices eros in cursus turpis massa tincidunt. Sit amet consectetur adipiscing elit duis tristique. Neque viverra justo nec ultrices dui sapien eget mi proin. Vitae aliquet nec ullamcorper sit. Consectetur purus ut faucibus pulvinar elementum integer. Duis at tellus at urna condimentum mattis pellentesque. Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Lacus sed turpis tincidunt id.",
    job_desc:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.",
    eligibility:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.",
    exp_yr: "2-3",
    salary: "50000",
    bg_img: `bg-[url('https://t3.ftcdn.net/jpg/05/79/48/52/360_F_579485255_hzHox0stuQmBx5QViwnQqQjk7RD2AJza.jpg')]`,
    job_title: "Product Manager",
    job_type: "Internship",
    location: "India",
    experience: "Fresher",
    time_posted: "4d",
    address: "12, Nico Robbin, Nicobar Islands",
  },
  {
    company_name: "Google",
    overview:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cursus turpis massa tincidunt dui ut. Lectus mauris ultrices eros in cursus turpis massa tincidunt. Sit amet consectetur adipiscing elit duis tristique. Neque viverra justo nec ultrices dui sapien eget mi proin. Vitae aliquet nec ullamcorper sit. Consectetur purus ut faucibus pulvinar elementum integer. Duis at tellus at urna condimentum mattis pellentesque. Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Lacus sed turpis tincidunt id.",
    job_desc:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.",
    eligibility:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.",
    exp_yr: "2-3",
    salary: "50000",
    bg_img: `bg-[url('https://t3.ftcdn.net/jpg/05/79/48/52/360_F_579485255_hzHox0stuQmBx5QViwnQqQjk7RD2AJza.jpg')]`,
    job_title: "App Developer",
    job_type: "Internship",
    location: "India",
    experience: "Fresher",
    time_posted: "4d",
    address: "12, Nico Robbin, Nicobar Islands",
  },
  {
    company_name: "Google",
    overview:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cursus turpis massa tincidunt dui ut. Lectus mauris ultrices eros in cursus turpis massa tincidunt. Sit amet consectetur adipiscing elit duis tristique. Neque viverra justo nec ultrices dui sapien eget mi proin. Vitae aliquet nec ullamcorper sit. Consectetur purus ut faucibus pulvinar elementum integer. Duis at tellus at urna condimentum mattis pellentesque. Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Lacus sed turpis tincidunt id.",
    job_desc:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.",
    eligibility:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.",
    exp_yr: "2-3",
    salary: "50000",
    bg_img: `bg-[url('https://t3.ftcdn.net/jpg/05/79/48/52/360_F_579485255_hzHox0stuQmBx5QViwnQqQjk7RD2AJza.jpg')]`,
    job_title: "Web Developer",
    job_type: "Internship",
    location: "India",
    experience: "Fresher",
    time_posted: "4d",
    address: "12, Nico Robbin, Nicobar Islands",
  },
  // {
  //   company_name: "Google",
  //   overview:
  //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cursus turpis massa tincidunt dui ut. Lectus mauris ultrices eros in cursus turpis massa tincidunt. Sit amet consectetur adipiscing elit duis tristique. Neque viverra justo nec ultrices dui sapien eget mi proin. Vitae aliquet nec ullamcorper sit. Consectetur purus ut faucibus pulvinar elementum integer. Duis at tellus at urna condimentum mattis pellentesque. Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Lacus sed turpis tincidunt id.",
  //   job_desc:
  //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.",
  //   eligibility:
  //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.",
  //   exp_yr: "2-3",
  //   salary: "50000",
  //   bg_img: `bg-[url('https://t3.ftcdn.net/jpg/05/79/48/52/360_F_579485255_hzHox0stuQmBx5QViwnQqQjk7RD2AJza.jpg')]`,
  //   job_title: "Software Developer",
  //   job_type: "Internship",
  //   location: "India",
  //   experience: "Fresher",
  //   time_posted: "4d",
  //   address: "12, Nico Robbin, Nicobar Islands",
  // },
  // {
  //   company_name: "Google",
  //   overview:
  //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cursus turpis massa tincidunt dui ut. Lectus mauris ultrices eros in cursus turpis massa tincidunt. Sit amet consectetur adipiscing elit duis tristique. Neque viverra justo nec ultrices dui sapien eget mi proin. Vitae aliquet nec ullamcorper sit. Consectetur purus ut faucibus pulvinar elementum integer. Duis at tellus at urna condimentum mattis pellentesque. Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Lacus sed turpis tincidunt id.",
  //   job_desc:
  //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.",
  //   eligibility:
  //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.",
  //   exp_yr: "2-3",
  //   salary: "50000",
  //   bg_img: `bg-[url('https://t3.ftcdn.net/jpg/05/79/48/52/360_F_579485255_hzHox0stuQmBx5QViwnQqQjk7RD2AJza.jpg')]`,
  //   job_title: "Software Developer",
  //   job_type: "Internship",
  //   location: "India",
  //   experience: "Fresher",
  //   time_posted: "4d",
  //   address: "12, Nico Robbin, Nicobar Islands",
  // },
  // {
  //   company_name: "Google",
  //   overview:
  //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cursus turpis massa tincidunt dui ut. Lectus mauris ultrices eros in cursus turpis massa tincidunt. Sit amet consectetur adipiscing elit duis tristique. Neque viverra justo nec ultrices dui sapien eget mi proin. Vitae aliquet nec ullamcorper sit. Consectetur purus ut faucibus pulvinar elementum integer. Duis at tellus at urna condimentum mattis pellentesque. Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Lacus sed turpis tincidunt id.",
  //   job_desc:
  //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.",
  //   eligibility:
  //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.",
  //   exp_yr: "2-3",
  //   salary: "50000",
  //   bg_img: `bg-[url('https://t3.ftcdn.net/jpg/05/79/48/52/360_F_579485255_hzHox0stuQmBx5QViwnQqQjk7RD2AJza.jpg')]`,
  //   job_title: "Software Developer",
  //   job_type: "Internship",
  //   location: "India",
  //   experience: "Fresher",
  //   time_posted: "4d",
  //   address: "12, Nico Robbin, Nicobar Islands",
  // },
  // {
  //   company_name: "Google",
  //   overview:
  //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cursus turpis massa tincidunt dui ut. Lectus mauris ultrices eros in cursus turpis massa tincidunt. Sit amet consectetur adipiscing elit duis tristique. Neque viverra justo nec ultrices dui sapien eget mi proin. Vitae aliquet nec ullamcorper sit. Consectetur purus ut faucibus pulvinar elementum integer. Duis at tellus at urna condimentum mattis pellentesque. Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Lacus sed turpis tincidunt id.",
  //   job_desc:
  //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.",
  //   eligibility:
  //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum. Laoreet sit amet cursus sit amet dictum sit. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Et netus et malesuada fames ac turpis egestas. Diam vulputate ut pharetra sit amet aliquam. Consectetur lorem donec massa sapien faucibus et. Amet tellus cras adipiscing enim. Quis hendrerit dolor magna eget est lorem ipsum dolor. Felis donec et odio pellentesque. Ut tellus elementum sagittis vitae et leo duis. Volutpat blandit aliquam etiam erat velit. Arcu risus quis varius quam quisque id diam vel. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu ultrices vitae auctor eu augue ut. Varius quam quisque id diam. Ac ut consequat semper viverra nam libero justo.",
  //   exp_yr: "2-3",
  //   salary: "50000",
  //   bg_img: `bg-[url('https://t3.ftcdn.net/jpg/05/79/48/52/360_F_579485255_hzHox0stuQmBx5QViwnQqQjk7RD2AJza.jpg')]`,
  //   job_title: "Software Developer",
  //   job_type: "Internship",
  //   location: "India",
  //   experience: "Fresher",
  //   time_posted: "4d",
  //   address: "12, Nico Robbin, Nicobar Islands",
  // },
];
